version: '3.9'

services:
  ginza-new-spacy:
    stdin_open: true
    tty: true
    volumes:
      - ../workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    container_name: ginza-new-spacy
    build:
      context: .
      dockerfile: Dockerfile